### ISSUE TITLE
PluginNotFoundException: The "views_view" entity type does not exist

### ISSUE THREAD

**Issue by romdouzegit** [yannickoo/menu_link_attributes#6] opened 2016-01-20 13:49 UTC
Hello,
thank you for this module,
Sorry if i'm not understandable, this is my first issue report on GitHub!

When i enable your module, and then try to access a Views page (whose link is provided by Views) here is the message i get:

> The website encountered an unexpected error. Please try again later.
> 
> Drupal\Component\Plugin\Exception\PluginNotFoundException: The "views_view" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 130 of core/lib/Drupal/Core/Entity/EntityTypeManager.php).
> 
> Drupal\Core\Entity\EntityRepository->loadEntityByUuid('views_view', 'views.nous_sommes_cornoualia.page_1')
> Drupal\Core\Entity\EntityManager->loadEntityByUuid('views_view', 'views.nous_sommes_cornoualia.page_1')
> menu_link_attributes_get_attributes(Object)
> menu_link_attributes_preprocess_menu(Array, 'menu__main', Array)
> Drupal\Core\Theme\ThemeManager->render('menu__main', Array)
> Drupal\Core\Render\Renderer->doRender(Array, )
> Drupal\Core\Render\Renderer->render(Array)
> Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1)
> __TwigTemplate_0d55fa8dc9e0732b6e892d7962282aac2736f6a4c869c6ce6bc980b75bbb7d21->block_content(Array, Array)
> Twig_Template->displayBlock('content', Array, Array)
> __TwigTemplate_0d55fa8dc9e0732b6e892d7962282aac2736f6a4c869c6ce6bc980b75bbb7d21->doDisplay(Array, Array)
> Twig_Template->displayWithErrorHandling(Array, Array)
> Twig_Template->display(Array)
> Twig_Template->render(Array)
> twig_render_template('core/themes/stable/templates/block/block--system-menu-block.html.twig', >Array)
> ...

Furthermore, when i try to edit the menu link, no attribute is available...

Did i miss something ?
Thank you

Romain

**Comment by dweidner** [comment] 2016-02-02 15:42
I have the same issue. The problem lies in the  `menu_link_attributes_get_attributes`-Function in `menu_link_attributes.module`.  The call of `loadEntityByUuid` will throw a `PluginNotFoundException` if trying to load an entity of a type that does does not exist (in this case `views_view`). I simply wrapped that method-call within a try and catch block. Not very elegant, but working for now.

``` php
 try {
    $entity = \Drupal::entityManager()->loadEntityByUuid($entity_type, $uuid);
  } catch(PluginNotfoundException $e) {
    return $attributes;
  }
```

Unfortunately I am to much of a starter in Drupal 8.  Hope you can come up with a better fix.

**Comment by dweidner** [comment] 2016-02-02 15:48
By the way #5, seems to fix that issue as well.  @zuuperman is fixing it by explicitly testing for menu_link_content as entity type [(22e6234:156)](https://github.com/zuuperman/menu_link_attributes/commit/22e62347e63852561d4d3d3320389ed8e13875c7#diff-9ebd1d0570bffde7db8323517dba67f9R156):

``` php
if ($entity_type == 'menu_link_content') {
  ...
}
```

**Comment by romdouzegit** [comment] 2016-02-05 08:24
Hi, thank you for your answer,
for my part, i decided (and managed !) to handle links attributes in my custom twig template.
Thank you again !

**Comment by dweidner** [comment] 2016-02-05 09:35
Glad you found a workaround. Nonetheless the issue still exists, so I would suggest not to close the issue.

**Comment by romdouzegit** [comment] 2016-02-05 09:36
Ho, yes, sorry, noob attitude !
I re-open !
Thx

**Comment by snufkin** [comment] 2016-02-24 10:18
We have that issue as well, it seems to be coming from an exported view. The error is

```
protected 'pluginId' => string 'views_view:views.contact_messages_administration.page_1' (length=55)
  protected 'pluginDefinition' => 
    array (size=16)
      'menu_name' => string 'admin' (length=5)
      'id' => string 'views_view:views.contact_messages_administration.page_1' (length=55)
      'parent' => string 'system.admin' (length=12)
      'route_name' => string 'view.contact_messages_administration.page_1' (length=43)
      'route_parameters' => 
        array (size=0)
          empty
      'url' => string '' (length=0)
      'title' => string 'Contact messages' (length=16)
      'description' => string 'Contact messages' (length=16)
      'class' => string 'Drupal\views\Plugin\Menu\ViewsMenuLink' (length=38)
      'options' => 
        array (size=0)
          empty
      'provider' => string 'views' (length=5)
      'enabled' => string '1' (length=1)
      'expanded' => string '0' (length=1)
      'weight' => string '0' (length=1)
      'metadata' => 
        array (size=2)
          'view_id' => string 'contact_messages_administration' (length=31)
          'display_id' => string 'page_1' (length=6)
      'form_class' => string 'Drupal\views\Plugin\Menu\Form\ViewsMenuLinkForm' (length=47)
```

which is odd, because there is no entity called views_view (to my knowledge).

Views constructs the menu link using the following pattern:

```
./core/modules/views/src/Plugin/views/display/Page.php:          $menu_link = 'views_view:views.' . $form_state->get('view')->id() . '.' . $form_state->get('display_id');
```

menu_link_attributes grabs the UUID by using

```
list($entity_type, $uuid) = explode(':', $plugin_id, 2);
$entity = \Drupal::entityTypeManager()->loadEntityByUuid($entity_type, $uuid);
```

which for instance in this case will return views_view as the $entity_type, and this will fail. For now I've resolved the issue by invoking

```
if ($entity_type != 'views_view') {
    $entity = \Drupal::entityTypeManager()
      ->loadEntityByUuid($entity_type, $uuid);
  }
```

as a workaround. Could the issue be that menu items provided by views are not entities? Or at least their plugin_id does not represent the entity type?

**Comment by snufkin** [comment] 2016-02-24 10:20
Actually I've just noticed that this is solved in the latest version by using

```
if ($entity_type == 'menu_link_content') {
```

so I think we can close the issue now.

**Comment by calebtr** [comment] 2016-04-20 20:45
I ran into a similar issue with a PluginNotFoundException being thrown when the Taxonomy Menu module was enabled. Updating to dev for Menu Link Attribute fixed the issue. 
At heart of the issue is this line in menu_link_attributes_get_attributes:

`list($entity_type, $uuid) = explode(':', $plugin_id, 2);`

The plugin ID doesn't necessarily include the name of the entity type. 

There is an open issue on documenting plugin IDs at https://www.drupal.org/node/2565045. So how do we properly get an entity type from a plugin ID? I'm not sure. 

The menu_link_content check that was added does the job of only acting on menu_link_content entities. If that's what we want here, ok by me. It may also be helpful to validate the UUID.

**Closed as completed** 2016-06-29 09:55 UTC
