### ISSUE TITLE
Adding managed_file field 

### ISSUE THREAD

**Issue by AMarwen** [yannickoo/menu_link_attributes#51] opened 2018-05-20 17:52 UTC
I'm using the D8 Menu Link Attributes module to add an attribute to a menu item using the yml configuration offered by the module ex:

attributes:
  title:
    label: 'Tooltip text'
    type: file
The code Above works fine, but the file is always downloaded to a temporary location, I have tried to set upload_location key but it seems not working :

attributes:
  image2:
    label: Image2
    type: managed_file
    upload_location: 'public://images/'

**Comment by yannickoo** [comment] 2018-11-08 14:41
Close this one because it's a duplicate of #50.

**Closed as completed by yannickoo** 2018-11-08 14:41 UTC
Labels: duplicate
