### ISSUE TITLE
Workaround - children items problem

### ISSUE THREAD

**Issue by odedltr** [yannickoo/menu_link_attributes#8] opened 2016-02-11 18:25 UTC
When adding attributes to a child item - the item won't rendered with the attributes.
To overcome this, add an attribute to the parent item and it will work great.
Can you fix this in the next version?

The issue is in function menu_link_attributes_preprocess_menu(), the condition of count($menu_link_attributes) prevent processing child items of none-attributes parents.

**Comment by otarza** [comment] 2016-03-03 19:18
+1

This was my workaround for child items, I implemented this hook in my module but it would be great if it will be fixed in next release.

`````` /**
 * Implements hook_preprocess_menu().
 */
function HOOK_preprocess_menu(&$variables) {
  foreach ($variables['items'] as &$item) {
    foreach ($item['below'] as &$below_item) {
      $menu_link_attributes = menu_link_attributes_get_attributes($below_item['original_link']);


      $url_attributes = $below_item['url']->getOption('attributes') ?: [];
      $attributes     = array_merge($url_attributes, $menu_link_attributes);

      $below_item['url']->setOption('attributes', $attributes);
    }
  }
}```
``````

**Comment by Soundvessel** [comment] 2016-06-29 00:18
+1 

@otarza That fix worked perfectly. Thanks!

This appears to be a duplicate of #9 

@yannickoo -- Is this module still actively maintained?

**Comment by yannickoo** [comment] 2016-06-29 09:27
@Soundvessel yeah this module is still maintained but this issue was not on my radar. Feel free to create a new pull requests over here so we can get this in 👍

**Closed as completed** 2016-06-29 09:40 UTC

**Comment by yannickoo** [comment] 2016-06-29 10:27
@Soundvessel for sure the module is actively maintained but it sometimes hard to find some time to work on issues. I started with fixing this issue and I managed it to close almost every open issue for this project 😇
